### ISSUE TITLE
client still crashing inside of Dim door when relogging crash log attached

### ISSUE THREAD

**Issue by kurokuno** [StevenRS11/DimDoors#103]
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT] java.lang.IllegalArgumentException: Could not get provider type for dimension 2, does not exist
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:157)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:311)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:209)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:62)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.multiplayer.NetClientHandler.func_72455_a(NetClientHandler.java:349)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.network.packet.Packet1Login.func_73279_a(Packet1Login.java:119)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(GuiConnecting.java:51)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1580)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.client.main.Main.main(SourceFile:101)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at java.lang.reflect.Method.invoke(Unknown Source)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[05:11:23 INFO]: Client> 2013-12-05 05:11:23 [INFO] [STDOUT]

**Comment by StevenRS11** [comment]
Fixed
