### ISSUE TITLE
Minecraft crashes after entering the nether

### ISSUE THREAD

**Issue by anagram3k** [StevenRS11/DimDoors#38]
I'm playing the 1.0.1 version of Hexxit. Already updated your mod, but doesn't helped. 

Found a nether portal created by a meteor crash. After using it, the minecraft crashed before showing the nether. Now it crashes everytime I loads the savegame. 
### Crash log below

Minecraft has crashed!      

Minecraft has stopped running because it encountered a problem; Unexpected error

A full error report has been saved to C:\Technic\data\hexxit\crash-reports\crash-2013-07-07_23.06.24-client.txt - Please include a copy of that file (Not this screen!) if you report this crash to anyone; without it, they will not be able to help fix the crash :(

--- BEGIN ERROR REPORT bd6bdeeb --------
Full report at:
C:\Technic\data\hexxit\crash-reports\crash-2013-07-07_23.06.24-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 07/07/13 23:06

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 108699968 bytes (103 MB) / 749142016 bytes (714 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xmx2048m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 Optifine OptiFine_1.5.2_HD_U_D5 63 mods loaded, 63 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.2.23.737} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.8.1.737} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.8.7} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHFramework{1.5.2.4} [CoFH Framework](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocks{55.0.1} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.5.2.28} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_bspkrsCore{v2.07(1.5.2)} [bspkrsCore]([1.5.2]bspkrsCorev2.07.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TreeCapitator{Forge 1.5.2.r01} [TreeCapitator]([1.5.2]TreeCapitator.Forge.1.5.2.r01.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.2.4} [CoFHCore](CoFHCore-1.5.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.2.4} [CoFHWorld](CoFHCore-1.5.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomLAN{2.2} [Custom LAN Mod](CustomPortForge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisMicroblocksInstallCheck{55.0.1} [Immibis's Microblocks (Check for incorrect installation)](immibis-microblocks-55.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{2.7.0.1} [Damage Indicators](1.5.2 DamageIndicators v2.7.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AsgardShield_Core{2.0.4} [AsgardShield](1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_Hallowed{2.0.0} [AS Addon- Hallowed](1.5.2ASAddonHallowed_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HarkenScythe_Core{2.1.6} [HarkenScythe](1.5.2HarkenScythe_v2.1.6Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_HarkenScythe{2.0.0} [AS Addon- HarkenScythe](1.5.2ASAddonHarkenScythe_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_NetherEnder{2.0.0} [AS Addon- Nether-Ender](1.5.2ASAddonNetherEnder_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ASAddon_ColorAPI{1.0.0} [ASAddon_ColorAPI](1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterStorage{0.6.2.23} [BetterStorage]([1.5.2]BetterStorage_0.6.2.23.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ArmorBarMod{0.7.1} [Armor Bar Mod](ArmorBarv0.7.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Artifice{1.5.2R1.1.1} [Artifice](Artifice-1.1.1-131.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Chisel{1.5.2R1.1.1} [Artifice Compat: Chisel](Artifice-1.1.1-131.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|EE3{1.5.2R1.1.1} [Artifice Compat: EE3](Artifice-1.1.1-131.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|MFR{1.5.2R1.1.1} [Artifice Compat: MFR](Artifice-1.1.1-131.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArtificeCompat|Vanilla{1.5.2R1.1.1} [Artifice Compat: Vanilla](Artifice-1.1.1-131.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{1.9.11} [Backpack](backpack-1.9.11-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_BackTools{1.5.2v1} [mod_BackTools](BackTools1.5.2v1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BattleTowers{1.3.4} [Battle Towers](BattleTowers_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterDungeons{1.8} [Better dungeons](BetterDungeons.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.3.1} [BiblioCraft](BiblioCraft[v1.3.1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_BuffBarMod{0.7.1} [Buff Bar Mod](BuffBarv0.7.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DimDoors{1.5.2R1.4.0RC1} [Dimensional Doors](DimensionalDoors-1.5.2R1.4.0RC1-160.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.15} [Enchanting Plus](EnchantingPlus-1.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.13.4} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    hexxitgear{1.5.2R1.0} [Hexxit Gear](HexxitGear-1.0-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{55.1.2} [Immibis Core](immibis-core-55.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfernalMobs{1.3.1} [Infernal Mobs](InfernalMobs_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.54b} [Inventory Tweaks](InventoryTweaks-1.54b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MapWriter{2.0} [MapWriter](mapwriter-2.0.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Meteors{2.10.2} [Falling Meteors](Meteors Mod V2.10.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    More Bows{1.5_v1} [More Bows mod](More bows 1.5.2_2 Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{1.5.1_2.1} [Natura](Natura_2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura|CompatMineFactoryReloaded{0.1} [Natura compat: MFR](Natura_2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.0.9.3} [NEI Plugins](NEIPlugins-1.0.9.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LegendGear{1.5.2} [LegendGear](NMcCoy-LegendGear-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ObsidiPlates{1.5.0} [Obsidian Pressure Plates](obsidiplates-1.5.2-universal-1.5.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OffLawn{1.0} [offLawn](OffLawn-1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Core{1.0.3.8} [Project Zulu Core](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Blocks{1.0.3.8} [Project Zulu Block and Items](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Dungeon{1.0.3.8} [Project Zulu Mobs](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Mobs{1.0.3.8} [Project Zulu Mobs](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|World{1.0.3.8} [Project Zulu World](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    xreliquary{1.5.2} [Xeno's Reliquary](Reliquary1.0.6d.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    rftl{1.0} [RottenFleshToLeather](RottenFleshToLeather-1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{10.3} [Ruins Spawning System](Ruins_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SoulShards{1.0.16} [Soul Shards](SoulShards-1.0.36-universal-srg.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.5.1_1.3.4.3} [Tinkers' Construct](TConstruct_1.3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR](TConstruct_1.3.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.18.1} [The Twilight Forest](twilightforest-1.18.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WildCaves3{0.4.2} [Wild Caves 3](WildCaves3-0.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chococraft{2.8.6} [Torojima's ChocoCraft](zzzChococraft_2.8.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LWJGL: 2.4.2
    OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

java.lang.NullPointerException
    at StevenDimDoors.mod_pocketDim.DimData.printAllLinkData(DimData.java:264)
    at StevenDimDoors.mod_pocketDim.EventHookContainer.onWorldLoad(EventHookContainer.java:83)
    at net.minecraftforge.event.ASMEventHandler_24_EventHookContainer_onWorldLoad_Load.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:69)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72455_a(NetClientHandler.java:333)
    at net.minecraft.network.packet.Packet1Login.func_73279_a(Packet1Login.java:119)
    at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1899)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:835)
    at net.minecraft.client.Minecraft.run(Minecraft.java:760)
    at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT f88cd394 ----------

**Comment by anagram3k** [comment]
Fixed the crash deleting DimensionalDoorsData and DimensionalDoorsDataOLD. 
If you need them, I have a copy and can attach it here.
