### ISSUE TITLE
Crash upon entering server (build 196)

### ISSUE THREAD

**Issue by iconmaster5326** [StevenRS11/DimDoors#60]
When I try to login to a server, the server's getting this error:

2013-07-31 13:56:33 [INFO] [STDERR] Cannot Hotload Dim: Could not get provider type for dimension 29, does not exist
2013-07-31 13:56:33 [INFO] [Minecraft-Server] iconmaster5326[/74.71.171.202:51700] logged in with entity id 171 at (234.9608089712607, 64.0, -25.44471983402036)
2013-07-31 13:56:33 [INFO] [STDERR] Cannot Hotload Dim: Could not get provider type for dimension 29, does not exist
2013-07-31 13:56:33 [INFO] [Minecraft-Server] Disconnecting iconmaster5326 [/74.71.171.202:51700]: Internal server error
2013-07-31 13:56:33 [SEVERE] [ForgeModLoader] Error handling login related packet - connection from iconmaster5326 [/74.71.171.202:51700] refused
java.lang.NullPointerException
at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(ServerConfigurationManager.java:120)
at net.minecraft.network.NetLoginHandler.completeConnection(NetLoginHandler.java:194)
at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:166)
at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:120)
at net.minecraft.network.NetLoginHandler.func_72529_d(NetLoginHandler.java:178)
at net.minecraft.network.NetLoginHandler.func_72532_c(NetLoginHandler.java:71)
at net.minecraft.server.ServerListenThread.func_71766_a(ServerListenThread.java:55)
at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:29)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:677)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
2013-07-31 13:56:33 [WARNING] [Minecraft-Server] Failed to handle packet for iconmaster5326 [/74.71.171.202:51700]: java.lang.NullPointerException
java.lang.NullPointerException
at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(ServerConfigurationManager.java:120)
at net.minecraft.network.NetLoginHandler.completeConnection(NetLoginHandler.java:194)
at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:166)
at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:120)
at net.minecraft.network.NetLoginHandler.func_72529_d(NetLoginHandler.java:178)
at net.minecraft.network.NetLoginHandler.func_72532_c(NetLoginHandler.java:71)
at net.minecraft.server.ServerListenThread.func_71766_a(ServerListenThread.java:55)
at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:29)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:677)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:275)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:573)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:470)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

I've recently moved some files between me and the server. I hope my stuff's not gone; my main base was in a pocket dimension...

**Comment by SenseiKiwi** [comment]
Steven responded to this issue on the Minecraft Forums thread for Dimensional Doors:

> Somehow, you got teleported into a dimension and then either the server crashed or was closed before it had a chance to save. This means that the server doesnt actually have a dimension registered for that ID- you need to delete your player.dat file on the server.

This issue is done.

**Comment by Laikulo** [comment]
~redacted~
needs it's own issue
