### ISSUE TITLE
Client crashing when connnecting to server after client restart when player had logged out inside a pocket dim

### ISSUE THREAD

**Issue by Laikulo** [StevenRS11/DimDoors#99]
When I attempt to connect after logging out inside a pocket dim, my client crashes as it is unable to find the correct dimension provider for the given dimension, it does not appear to be getting it from the server.

If I modify my player.dat to get out of the dim, it works just fine, and the dim is not deleted, just the client crashes.  I will take a look into the source and see if i can find an idea

Server: MCPC+ (Build 97) (gson added to classpath)
Mod Version: Reports as 1.5.2R1.4.1RC1 but labeled as 2.1.0 beta

Crash Report Follows:

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/8/13 9:00 PM
Description: Ticking screen

java.lang.IllegalArgumentException: Could not get provider type for dimension 4, does not exist
    at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:157)
    at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:311)
    at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:209)
    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:62)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72455_a(NetClientHandler.java:349)
    at net.minecraft.network.packet.Packet1Login.func_73279_a(Packet1Login.java:119)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(GuiConnecting.java:51)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1578)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:908)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:836)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:157)
    at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:311)
    at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:209)
    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:62)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72455_a(NetClientHandler.java:349)
    at net.minecraft.network.packet.Packet1Login.func_73279_a(Packet1Login.java:119)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(GuiConnecting.java:51)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1578)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:908)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:836)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
[[snip]]
```

**Comment by Cisien** [comment]
I get the same thing on 1.6.4 with forge 946 (No MCPC)

```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 11/13/13 6:31 PM
Description: Ticking screen

java.lang.IllegalArgumentException: Could not get provider type for dimension 16, does not exist
    at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:157)
    at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:311)
    at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:209)
    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:62)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72455_a(NetClientHandler.java:349)
    at net.minecraft.network.packet.Packet1Login.func_73279_a(Packet1Login.java:119)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(GuiConnecting.java:51)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1580)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:157)
    at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:311)
    at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:209)
    at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:62)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72455_a(NetClientHandler.java:349)
    at net.minecraft.network.packet.Packet1Login.func_73279_a(Packet1Login.java:119)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:281)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(GuiConnecting.java:51)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1580)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2574234912 bytes (2454 MB) / 3040280576 bytes (2899 MB) up to 3040280576 bytes (2899 MB)
    JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xms3G -XX:MaxPermSize=382M -XX:PermSize=382M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.41.946 Minecraft Forge 9.11.1.946 113 mods loaded, 113 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.4.41.946} [Forge Mod Loader] (minecraftforge-9.11.1.946.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.11.1.946} [Minecraft Forge] (minecraftforge-9.11.1.946.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppliedEnergistics-Core{rv14.finale} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{0.9.0.6} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisMicroblocks{57.2.3} [Immibis's Microblocks] (immibis-microblocks-57.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.6.1.5} [Not Enough Items] (NotEnoughItems 1.6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PowerCrystalsCore{1.1.8} [PowerCrystals Core] (PowerCrystalsCore-1.1.8-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    switches|pistontweak{1.3.0 build 25} [Switches|PistonTweak] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IC2{2.0.299-experimental} [IndustrialCraft 2] (industrialcraft-2_2.0.299-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisCore{57.1.4} [Immibis Core] (immibis-core-57.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AdvancedRepulsionSystems{57.0.0} [Advanced Repulsion Systems] (adv-repulsion-systems-57.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AdvancedMachines{57.0.0} [Advanced Machines] (advanced-machines-57.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppliedEnergistics{rv14.finale} [Applied Energistics] (appeng-rv14-finale-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ArchimedesShipsMod{1.6.4 v1.4.5} [Archimedes' Ships] (ArchimedesShips 1.4.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.5.1} [BiblioCraft] (BiblioCraft[v1.5.1].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiomesOPlenty{1.1.3} [Biomes O' Plenty] (BiomesOPlenty-universal-1.6.4-1.1.3.212.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioWoodsBoP{1.3} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core{4.1.2} [BuildCraft] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders{4.1.2} [BC Builders] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy{4.1.2} [BC Energy] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory{4.1.2} [BC Factory] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport{4.1.2} [BC Transport] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded{1.6.2R2.7.2B1} [MineFactory Reloaded] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForestryPre{1.6.2R2.7.2B1} [MFR Compat: Forestry (part 2)] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forestry{2.3.0.7} [Forestry for Minecraft] (forestry-A-2.3.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioWoodsForestry{1.3} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.3].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BinnieCore{1.8-dev2} [Binnie Core] (binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraBees{1.8-dev2} [Extra Bees] (binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraTrees{1.8-dev2} [Extra Trees] (binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon{4.1.2} [BC Silicon] (buildcraft-A-1.6.2-4.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{v1.9.4} [Carpenter's Blocks] (Carpenter's Blocks v1.9.4 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ChickenChunks{1.3.3.3} [ChickenChunks] (ChickenChunks 1.3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CompactSolars{4.4.19.214} [Compact Solar Arrays] (compactsolars-universal-1.6.4-4.4.19.214.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ComputerCraft{1.57} [ComputerCraft] (ComputerCraft1.57.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CCTurtle{1.57} [ComputerCraft Turtles] (ComputerCraft1.57.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderStorage{1.4.3.5} [EnderStorage] (EnderStorage 1.4.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization{0.8.08} [Factorization] (Factorization-0.8.08.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Railcraft{8.2.0.0} [Railcraft] (Railcraft_1.6.2-8.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DartCraft{Beta 0.2.12} [DartCraft] (DartCraft Beta 0.2.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DimensionalAnchors{57.0.0} [Dimensional Anchors] (dimensional-anchor-57.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    dimdoors{1.6.2R2.1.1RC1} [Dimensional Doors] (DimensionalDoors-1.6.2R2.1.1RC1-10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EE3{@VERSION@ (build @BUILD_NUMBER@)} [Equivalent Exchange 3] (ee3-universal-pre2a-30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderIO{0.4.2} [Ender IO] (EnderIO-1.6.4-0.4.2.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{0.3.5} [Extra Utilities] (extrautils - 0.3.5.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization.misc{0.8.08} [Factorization Miscellaneous Nonsense] (Factorization-0.8.08.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization.notify{0.8.08} [Factorization Notification System] (Factorization-0.8.08.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    factorization.dimensionalSlice{0.8.08} [Factorization Dimensional Slices] (Factorization-0.8.08.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FinndusFillies{1.0.0} [Finndus Fillies] (FinndusFillies-1.6.2-universal-1.0.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{2.2.0} [iChunUtil] (iChunUtil2.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GraviGun{2.0.0} [GraviGun] (GravityGun2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IC2NuclearControl{1.6.2c} [Nuclear Control] (IC2NuclearControl-1.6.2c-ic2-experimental.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ImmibisPeripherals{57.0.0} [Immibis's Peripherals] (immibis-peripherals-57.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    InfiniTubes{57.0.2} [InfiniTubes] (infinitubes-57.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.56} [Inventory Tweaks] (InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IronChest{5.4.1.639} [Iron Chest] (ironchest-universal-1.6.4-5.4.1.639.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.6.X_1.5.1d} [Tinkers' Construct] (TConstruct_1.6.4_1.5.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MagicBees{2.1.7} [Magic Bees] (magicbees-2.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.2R2.7.2B1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatAtum{1.6.2R2.7.2B1} [MFR Compat: Atum] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBackTools{1.6.2R2.7.2B1} [MFR Compat: BackTools] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBiomesOPlenty{1.6.2R2.7.2B1} [MFR Compat: Biomes O' Plenty] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatBuildCraft{1.6.2R2.7.2B1} [MFR Compat: BuildCraft] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatChococraft{1.6.2R2.7.2B1} [MFR Compat: Chococraft] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatExtraBiomes{1.6.2R2.7.2B1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatForestry{1.6.2R2.7.2B1} [MFR Compat: Forestry] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatIC2{1.6.2R2.7.2B1} [MFR Compat: IC2] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatMagicalCrops{1.6.2R2.7.2B1} [MFR Compat: Magical Crops] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mystcraft{0.10.10.00} [Mystcraft] (mystcraft-uni-1.6.4-0.10.10.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatMystcraft{1.6.2R2.7.2B1} [MFR Compat: Mystcraft] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatPams{1.6.2R2.7.2B1} [MFR Compat: Pam's Mods] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRailcraft{1.6.2R2.7.2B1} [MFR Compat: Railcraft] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatRP2{1.6.2R2.7.2B1} [MFR Compat: RP2] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.6.2R2.7.2B1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatThaumcraft{1.6.2R2.7.2B1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatTwilightForest{1.6.2R2.7.2B1} [MFR Compat: TwilightForest] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatVanilla{1.6.2R2.7.2B1} [MFR Compat: Vanilla] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MineFactoryReloaded|CompatXyCraft{1.6.2R2.7.2B1} [MFR Compat: XyCraft] (MineFactoryReloaded-2.7.2B1-115.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    numina{0.0.1-28} [Numina] (Numina-1.6.2-0.0.1-28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    powersuits{0.8.0-36} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.6.2-0.8.0-36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Morph{0.3.0} [Morph] (Morph-Beta-0.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons{1.9.2.r44} [NEI Addons] (neiaddons-1.6.2-1.9.2.r44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|AE{1.9.2.r44} [NEI Addons: Applied Energistics] (neiaddons-1.6.2-1.9.2.r44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|CraftingTables{1.9.2.r44} [NEI Addons: Crafting Tables] (neiaddons-1.6.2-1.9.2.r44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|ExtraBees{1.9.2.r44} [NEI Addons: Extra Bees] (neiaddons-1.6.2-1.9.2.r44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|Forestry{1.9.2.r44} [NEI Addons: Forestry] (neiaddons-1.6.2-1.9.2.r44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIAddons|MiscPeripherals{1.9.2.r44} [NEI Addons: Misc Peripherals] (neiaddons-1.6.2-1.9.2.r44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIPlugins{1.1.0.4} [NEI Plugins] (NEIPlugins-1.1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ObsidiPlates{2.0.0} [Obsidian Pressure Plates] (obsidiplates-1.6.2-universal-2.0.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenPeripheral{0.2.1} [OpenPeripheral] (OpenPeripheral-0.2.1-forge9.11.0.883-snapshot-73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenBlocks{1.2.0} [OpenBlocks] (OpenBlocks-1.2.0-forge9.11.0.883-snapshot-393.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    PortalGun{2.0.1} [PortalGun] (PortalGun2.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RedLogic{57.2.1} [RedLogic] (redlogic-57.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    JAKJ_RedstoneInMotion{2.3.0.0} [Redstone In Motion] (RedstoneInMotion_2.3.0.0_mc1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    StevesCarts{2.0.0.a133} [Steve's Carts 2] (StevesCarts2.0.0.a133.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    switches{1.3.0} [Switches] (switches-1.6.4-universal-coremod-1.3.0.25.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.0.0.193} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.0.193.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct|ForgeMuliPart{0.1} [TConstruct Compat: FMP] (TConstruct_1.6.4_1.5.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct|CompatMineFactoryReloaded{0.2} [TConstruct Compat: MFR] (TConstruct_1.6.4_1.5.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct|NotEnoughItems{0.1} [TConstruct Compat: NEI] (TConstruct_1.6.4_1.5.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct|CompatWaila{0.0.1} [TConstruct Compat: Waila] (TConstruct_1.6.4_1.5.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Translocator{1.1.0.13} [Translocator] (Translocator 1.1.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Tubestuff{57.0.2} [Tubestuff] (tubestuff-57.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    UsefulFood{1.4.4} [UsefulFood] (UsefulFood-1.6.2_1.4.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Core{1.4.0.6} [WR-CBE Core] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Addons{1.4.0.6} [WR-CBE Addons] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    WR-CBE|Logic{1.4.0.6} [WR-CBE Logic] (WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ZanMinimap{0.9.4} [Zan's Minimap] (ZansMinimap1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.0.0.193} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.0.193.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.0.0.193} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.0.193.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct Environment: Sane and ready for action. Bugs may be reported.
    Launched Version: 1.6.4-Forge9.11.1.946
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Soartex_Fanver.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
```

**Comment by StevenRS11** [comment]
Fixed
